### ISSUE TITLE
SensorEvent is not declared

### ISSUE THREAD

**Issue by alesaccoia** [danthemellowman/ofxCardboard#1]
SensorEvent isn't declared anywhere, the android project doesn't compile..

In file included from src/headTracking.cpp:8:0:
src/headTracking.h:19:29: error: 'SensorEvent' has not been declared
     void processSensorEvent(SensorEvent event);

**Comment by danthemellowman** [comment]
Correct. This uses my own version of openFrameworks I haven't pushed. This
is for my own development and it is not finished.
